server:
  port: 8090
spring:
  datasource:
    username: root
    password: root
    name: customer_data
    url: jdbc:mysql://localhost:3306/customer_data
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

logging:
  level:
    org.springframework.data: TRACE
